---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-matrix-mas-secrets
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: matrix-mas-secrets
    creationPolicy: Owner
  data:
  - secretKey: oidc-client-secret
    remoteRef:
      key: kubernetes/data/apps/matrix
      property: mas_oidc_client_secret
  - secretKey: matrix-secret
    remoteRef:
      key: kubernetes/data/apps/matrix
      property: mas_matrix_secret
  - secretKey: encryption
    remoteRef:
      key: kubernetes/data/apps/matrix
      property: mas_encryption
  - secretKey: keys.yaml
    remoteRef:
      key: kubernetes/data/apps/matrix
      property: mas_keys_yaml

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-matrix-mas-cross-secrets
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cross-secret-store
    kind: ClusterSecretStore
  target:
    name: matrix-mas-cross-secrets
    creationPolicy: Owner
  data:
  - secretKey: postgres-password
    remoteRef:
      key: cross/data/apps/matrix
      property: mas_postgres_password
