---
apiVersion: v1
kind: Service
metadata:
  name: matrix-mas
  namespace: apps
  labels:
    app: matrix-mas
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: matrix-mas
