---
services:
  vault:
    image: hashicorp/vault:2.0.1@sha256:7553550027156b8f04e81f61a98c3f53a7bce57104f2a400e2012c851f66ac19
    container_name: vault
    user: "0:0"
    ports:
      - "8200:8200"
    volumes:
      - ./config:/vault/config
      - ./data:/vault/file
      - ./init-vault.sh:/init-vault.sh
    cap_add:
      - IPC_LOCK
      - SETFCAP
    command: "vault server -config=/vault/config/vault-config.json"
    restart: unless-stopped
