---
services:
  vault:
    image: hashicorp/vault:2.0.3@sha256:a296a888b118615dc01d5f1a6846e6d4a7277946caaed5b447008fff5fe06b54
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./config:/vault/config
      - ./data:/vault/file
      - ./init-vault.sh:/init-vault.sh
    environment:
      SKIP_SETCAP: "true"
    cap_add:
      - IPC_LOCK
    command: "vault server -config=/vault/config/vault-config.json"
    restart: unless-stopped
