---
services:
  vault:
    image: hashicorp/vault:2.1.1@sha256:47f14a6acb98f48d798a07df7c83f23a6e636e1cf724c5f8ff165cb32667a1e2
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./config:/vault/config
      - ./data:/vault/file
      - ./init-vault.sh:/init-vault.sh
    environment:
      SKIP_SETCAP: "true"
    cap_add:
      - IPC_LOCK
    command: "vault server -config=/vault/config/vault-config.json"
    restart: unless-stopped
