---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mautrix-discord-config
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  config.yaml: |
    # https://docs.mau.fi/bridges/go/setup.html?bridge=discord
    # https://docs.mau.fi/bridges/general/docker-setup.html?bridge=discord
    homeserver:
      address: http://matrix-synapse.apps.svc.cluster.local:8008
      domain: matrix.ildoc.it
      software: standard
      async_media: false
      websocket: false
      ping_interval_seconds: 0

    appservice:
      address: http://mautrix-discord.apps.svc.cluster.local:29334
      hostname: 0.0.0.0
      port: 29334
      database:
        type: postgres
        uri: "postgres://matrix_discord_user:${DISCORD_POSTGRES_PASSWORD}@192.168.0.30:5432/matrix_discord_db?sslmode=disable"
        max_open_conns: 10
        max_idle_conns: 2
        max_conn_idle_time: null
        max_conn_lifetime: null
      id: discord
      bot:
        username: discordbot
        displayname: Discord bridge bot
        avatar: mxc://maunium.net/nIdEykemnwdisvHbpxflpDlC
      ephemeral_events: true
      async_transactions: false
      as_token: "${DISCORD_AS_TOKEN}"
      hs_token: "${DISCORD_HS_TOKEN}"

    bridge:
      username_template: "discord_{{.}}"
      displayname_template: "{{if .Webhook}}Webhook{{else}}{{or .GlobalName .Username}}{{if .Bot}} (bot){{end}}{{end}}"
      channel_name_template: "{{if or (eq .Type 3) (eq .Type 4)}}{{.Name}}{{else}}#{{.Name}}{{end}}"
      guild_name_template: "{{.Name}}"
      private_chat_portal_meta: default
      public_address: null
      avatar_proxy_key: "${DISCORD_AVATAR_PROXY_KEY}"
      portal_message_buffer: 128
      startup_private_channel_create_limit: 5
      delivery_receipts: false
      message_status_events: false
      message_error_notices: true
      restricted_rooms: false
      autojoin_thread_on_open: true
      embed_fields_as_tables: true
      mute_channels_on_create: false
      sync_direct_chat_list: false
      resend_bridge_info: false
      custom_emoji_reactions: true
      delete_portal_on_channel_delete: false
      delete_guild_on_leave: true
      federate_rooms: true
      prefix_webhook_messages: true
      enable_webhook_avatars: false
      use_discord_cdn_upload: true
      forbid_dming_strangers: true
      cache_media: unencrypted
      direct_media:
        enabled: false
      animated_sticker:
        target: webp
        args:
          width: 320
          height: 320
          fps: 25
      double_puppet_server_map: {}
      double_puppet_allow_discovery: false
      login_shared_secret_map: {}
      command_prefix: "!discord"
      management_room_text:
        welcome: "Hello, I'm a Discord bridge bot."
        welcome_connected: "Use `help` for help."
        welcome_unconnected: "Use `help` for help or `login` to log in."
        additional_help: ""
      backfill:
        forward_limits:
          initial:
            dm: 10
            channel: 0
            thread: 0
          missed:
            dm: 10
            channel: 0
            thread: 0
        max_guild_members: -1
      # MAS-compatible device creation (MSC4190)
      # https://docs.mau.fi/bridges/general/end-to-bridge-encryption.html
      encryption:
        allow: true
        default: false
        appservice: false
        msc4190: true
        require: false
        allow_key_sharing: true
        plaintext_mentions: false
        verification_levels:
          receive: unverified
          send: unverified
          share: cross-signed-tofu
        rotation:
          enable_custom: false
          milliseconds: 604800000
          messages: 100
        disable_device_change_key_rotation: false
      provisioning:
        prefix: /_matrix/provision
        shared_secret: "${DISCORD_PROVISIONING_SECRET}"
        debug_endpoints: false
      permissions:
        "@filippo:matrix.ildoc.it": admin
        "matrix.ildoc.it": user

    logging:
      min_level: info
      writers:
        - type: stdout
          format: pretty-colored
