---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-mautrix-discord-secrets
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: mautrix-discord-secrets
    creationPolicy: Owner
  data:
  - secretKey: as-token
    remoteRef:
      key: kubernetes/data/apps/mautrix-discord
      property: as_token
  - secretKey: hs-token
    remoteRef:
      key: kubernetes/data/apps/mautrix-discord
      property: hs_token
  - secretKey: provisioning-secret
    remoteRef:
      key: kubernetes/data/apps/mautrix-discord
      property: provisioning_secret
  - secretKey: avatar-proxy-key
    remoteRef:
      key: kubernetes/data/apps/mautrix-discord
      property: avatar_proxy_key
  - secretKey: registration.yaml
    remoteRef:
      key: kubernetes/data/apps/mautrix-discord
      property: registration_yaml

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-mautrix-discord-cross-secrets
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cross-secret-store
    kind: ClusterSecretStore
  target:
    name: mautrix-discord-cross-secrets
    creationPolicy: Owner
  data:
  - secretKey: postgres-password
    remoteRef:
      key: cross/data/apps/mautrix-discord
      property: postgres_password
