---
apiVersion: v1
kind: Service
metadata:
  name: mautrix-discord
  namespace: apps
  labels:
    app: mautrix-discord
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  # https://docs.mau.fi/bridges/general/docker-setup.html — k8s notes
  publishNotReadyAddresses: true
  type: ClusterIP
  ports:
    - port: 29334
      targetPort: 29334
      protocol: TCP
      name: appservice
  selector:
    app: mautrix-discord
