---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: split-secret
  namespace: apps
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cross-secret-store
    kind: ClusterSecretStore
  target:
    name: split-secret
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: cross/data/apps/split
        property: db_password
    - secretKey: jwt-key
      remoteRef:
        key: cross/data/apps/split
        property: jwt_key
    - secretKey: resend-api-key
      remoteRef:
        key: cross/data/apps/split
        property: resend_api_key
    - secretKey: admin-email
      remoteRef:
        key: cross/data/apps/split
        property: admin_email
    - secretKey: admin-password
      remoteRef:
        key: cross/data/apps/split
        property: admin_password

