---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-web-automated
  namespace: apps
spec:
  selector:
    matchLabels:
      app: calibre-web-automated
  strategy:
    type: Recreate
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: calibre-web-automated
    spec:
      containers:
        - name: calibre-web-automated
          image: crocodilestick/calibre-web-automated
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Rome"
            - name: NETWORK_SHARE_MODE
              value: "true"
            - name: HARDCOVER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cwa-k8s-secrets
                  key: hardcover-token
          volumeMounts:
            - name: data
              mountPath: /config
              subPath: config
            - name: data
              mountPath: /config/.config/calibre/plugins
              subPath: plugins
            - name: books
              mountPath: /calibre-library
            - name: books-ingest
              mountPath: /cwa-book-ingest
          resources:
            limits:
              cpu: 50m
              memory: 1Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: calibre-web-automated
        - name: books
          nfs:
            server: 192.168.0.123
            path: /mnt/mediadisk/books
        - name: books-ingest
          nfs:
            server: 192.168.0.123
            path: /mnt/mediadisk/books-ingest
