---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-cwa-k8s-secrets
  namespace: apps
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: cwa-k8s-secrets
    creationPolicy: Owner
  data:
  - secretKey: hardcover-token
    remoteRef:
      key: kubernetes/data/apps/calibre-web-automated
      property: hardcover_token
