---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-shelfmark-secrets
  namespace: apps
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-kubernetes-secret-store
    kind: ClusterSecretStore
  target:
    name: shelfmark-secrets
    creationPolicy: Owner
  data:
  - secretKey: prowlarr-api-key
    remoteRef:
      key: kubernetes/data/apps/shelfmark
      property: prowlarr_api_key
