---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-storage
